// <auto-generated />
using System;
using FileConverter.DatabaseProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileConverter.DatabaseProvider.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileConverter.DatabaseProvider.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DOLocationID")
                        .HasColumnType("integer");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("PULocationID")
                        .HasColumnType("integer");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("integer");

                    b.Property<string>("StoreAndFwdFlag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TpepDropoffDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TpepPickupDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TripDistance")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
